apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "push.fullname" . }}
  labels:
    {{- include "push.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "push.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "push.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: push
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          volumeMounts:
            - name: firebase-service-account
              mountPath: {{ .Values.firebase.serviceAccountFilePath | quote }}
              subPath: {{ .Values.firebase.serviceAccountKey | quote }}
              readOnly: true
          {{- if .Values.envFrom.secrets }}
          envFrom:
            {{- range .Values.envFrom.secrets }}
            - secretRef:
                name: {{ . | quote }}
            {{- end }}
          {{- end }}
          {{- if .Values.env }}
          env:
            {{- toYaml .Values.env | nindent 12 }}
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: firebase-service-account
          secret:
            secretName: {{ .Values.firebase.serviceAccountSecretName | quote }}
