replicaCount: 1

image:
  repository: frogfrog243/notify-gateway
  tag: "latest"
  pullPolicy: Always

service:
  type: ClusterIP
  port: 80
  targetPort: 8080

ingress:
  enabled: true
  className: nginx
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
  host: notifications.64v.ru
  path: /
  pathType: Prefix
  tls:
    enabled: true
    secretName: notifications-64v-ru-tls

resources: {}
nodeSelector: {}
tolerations: []
affinity: {}

env:
  - name: Serilog__WriteTo__0__Name
    value: Console
  - name: Serilog__WriteTo__1__Name
    value: File
  - name: Serilog__WriteTo__1__Args__path
    value: /logs/notify-gateway-.log
  - name: Serilog__WriteTo__1__Args__rollingInterval
    value: Day
envFrom:
  secrets:
    - notify-system-db
    - notify-rabbitmq-env
  configMaps: []
